### ISSUE TITLE
Error when run the code

### ISSUE THREAD

**Issue by lqq119119** [kite1988/famf#2]
Hi,when I follow your README , I don't know how to set the configuration file.
At the same time , I also don't know how to compile those java source code.When I try to compile them, the computer tell me that 'it cannot find happy.coding.io , com.google.common.collect , com.google.common.cache , com.google.common.collect.Table' and the computer also cannot find a lot of classes like 'BiMap , DataDAO ,  Multimap , SparseMatrix' and so on .
So how can i solve these problems? Please give me some instruction,thank you.

**Comment by kite1988** [comment]
1. I have added comments on the configuration files to guide you set the parameters.
2. The error is caused by the missing of some jar files. You should include all the jar files in the "lib" folder in classpath.

I also have updated the README for clearer instruction.
