### ISSUE TITLE
Error when use the code 

### ISSUE THREAD

**Issue by lqq119119** [kite1988/famf#3]
Hi, today I try to use your code again with your new tutorial, but when I use the command line and input "java -cp "lib/*":bin main.TextMain.java conf/TextMain.conf" , the computer tells me that "it cannot find or load the main class  main.TextMain.java" , I don't kow what to do next, can you give me some instructions please? Thank you.

**Comment by kite1988** [comment]
Please run the following command instead. I have fixed this in readme.
java -cp "lib/*":bin main.TextVisualMain conf/text_visual.conf
